# Generated by Django 4.1.4 on 2023-01-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.coupon",
            ),
        ),
    ]
