# Generated by Django 4.1.4 on 2023-01-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_shoppingcart_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
