# Generated by Django 4.1.4 on 2023-01-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_coupon_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="total",
            field=models.FloatField(blank=True, null=True, verbose_name="Total amount"),
        ),
    ]
