# Generated by Django 4.1.4 on 2023-01-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_shoppingcart_total"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={
                "ordering": ("created_at", "is_paid"),
                "verbose_name": "Shopping cart",
                "verbose_name_plural": "Shopping carts",
            },
        ),
    ]
