# Generated by Django 4.1.4 on 2023-01-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="BlogCategory",
        ),
    ]
